using System.Text;

namespace PKForge.Domain;

/// <summary>
/// Everything that changes how a Pokémon looks, beyond species / form / shiny. All default
/// to "plain" so a caller that genuinely only knows the species (a dex grid) stays simple.
/// </summary>
/// <param name="Female">The entity is female (gender 1): picks gender-difference art (Hippowdon, Pikachu, Meowstic HOME...).</param>
/// <param name="FormArgument">PKHeX IFormArgument: Alcremie's sweet decoration (0-6).</param>
/// <param name="Cosplay">Gen 6 Pikachu: forms 1-6 are the ORAS cosplay outfits, not the Gen 7 caps.</param>
/// <param name="Gigantamax">Draw the Gigantamax look (callers set it only where G-Max art is wanted).</param>
public readonly record struct SpriteTraits(bool Female = false, int FormArgument = 0, bool Cosplay = false, bool Gigantamax = false);

/// <summary>The complete visual key of one Pokémon, shared by every sprite surface.</summary>
public readonly record struct SpriteLook(int Species, int Form, bool Shiny, SpriteTraits Traits = default)
{
    /// <summary>Stable cache key: two looks that resolve differently never share one.</summary>
    public string CacheKey => $"{Species}-{Form}-{(Shiny ? 1 : 0)}-{(Traits.Female ? 1 : 0)}-{Traits.FormArgument}-{(Traits.Cosplay ? 1 : 0)}-{(Traits.Gigantamax ? 1 : 0)}";

    /// <summary>
    /// Builds a look from raw entity fields the way PKHeX reads them: gender 1 is female;
    /// Gen 6 (PK6) Pikachu forms are cosplay outfits.
    /// </summary>
    public static SpriteLook Of(int species, int form, bool shiny, int gender = 0, uint formArgument = 0, int generation = 0) =>
        new(species, form, shiny, new SpriteTraits(
            Female: gender == 1,
            FormArgument: species == SpriteCatalog.Alcremie ? (int)Math.Min(formArgument, 6u) : 0,
            Cosplay: species == SpriteCatalog.Pikachu && generation == 6 && form is >= 1 and <= 6));
}

/// <summary>How faithful the resolved art is to the requested look (strongest first).</summary>
public enum SpriteFidelity
{
    /// <summary>The exact form, shiny state and gender art.</summary>
    Exact,
    /// <summary>Exact form and shiny state; the gender-difference art does not exist in this set.</summary>
    GenderMissing,
    /// <summary>Exact form; no shiny art exists in this set (the app still draws its shiny sparkle).</summary>
    ShinyMissing,
    /// <summary>The form has no art at all in this set: the base form stands in.</summary>
    BaseForm,
    /// <summary>Nothing for the species: the "?" placeholder.</summary>
    Unknown,
}

/// <summary>One asset to try, in order, and how faithful it is.</summary>
public readonly record struct SpriteCandidate(string Path, SpriteFidelity Fidelity);

/// <summary>
/// The one sprite-key resolver. Maps a <see cref="SpriteLook"/> onto:
/// <list type="bullet">
/// <item>bundled PKHeX pixel sprites / artwork, named exactly like
/// PKHeX.Drawing.PokeSprite SpriteName.GetResourceStringSprite (form, 'c' cosplay, 'p' Let's Go
/// starter, 'f' gendered art, Alcremie cream-sweet, 's' shiny);</item>
/// <item>PokeAPI HOME renders and Showdown animations, whose files are named by PokeAPI
/// pokemon id / form identifier. The PKHeX-form → PokeAPI-file table is generated by
/// tools/SpriteForms/build.py from PKHeX FormConverter names and PokeAPI pokemon_forms.csv,
/// with each file's shiny / female availability taken from the PokeAPI/sprites tree.</item>
/// </list>
/// Fallback is explicit and ordered by fidelity: a remote source returns null when it has no
/// art for the exact form (the caller drops to the next source instead of showing a wrong
/// form in high resolution); only the bundled chain ends on the base form, and says so.
/// </summary>
public static class SpriteCatalog
{
    public const int Pikachu = 25;
    public const int Eevee = 133;
    public const int Alcremie = 869;

    /// <summary>PKHeX SpriteName.SpeciesDefaultFormSprite: species PKHeX draws with the base sprite for every form.</summary>
    private static readonly HashSet<int> DefaultFormSprite = [414, 664, 665, 744, 778, 854, 855, 892, 982, 1012, 1013];

    /// <summary>
    /// Of <see cref="DefaultFormSprite"/>, the species whose forms really look alike at sprite
    /// scale (wing pattern, authenticity mark, Own Tempo); folding them is exact. The others
    /// (Mimikyu Busted, Urshifu Rapid Strike, three-segment Dudunsparce) differ visibly, so a
    /// fold there is reported as <see cref="SpriteFidelity.BaseForm"/>.
    /// </summary>
    private static readonly HashSet<int> IdenticalForms = [414, 664, 665, 744, 854, 855, 1012, 1013];

    /// <summary>
    /// PKHeX FormInfo.IsTotemForm / GetTotemBaseForm: totems draw as their base form (PKHeX adds a
    /// glow). Raticate / Marowak totem is form 2 → Alolan (1); Mimikyu totems 2/3 → 0; others 1 → 0.
    /// </summary>
    public static int? TotemBaseForm(int species, int form) => species switch
    {
        778 when form is 2 or 3 => 0,
        20 or 105 when form == 2 => 1,
        735 or 738 or 743 or 752 or 754 or 758 or 777 or 784 when form == 1 => 0,
        _ => null,
    };

    /// <summary>PKHeX SpriteName.SpeciesGenderedSprite: species with female pixel art ('f').</summary>
    private static readonly HashSet<int> GenderedSprite = [449, 450, 521, 592, 593, 668];

    private static readonly Lazy<IReadOnlyDictionary<string, RemoteEntry>> Table = new(Load);

    /// <summary>The raw generated table: key → HOME / Showdown stems and variant flags.</summary>
    public static IReadOnlyDictionary<string, RemoteEntry> Entries => Table.Value;

    // ───────────────────────── bundled PKHeX sprites ─────────────────────────

    /// <summary>
    /// PKHeX's resource name for a look without the 'b'/'a' prefix, e.g. "_6_2s", "_869_0_3",
    /// "_25_1c". Mirrors SpriteName.GetResourceStringSprite (PKHeX.Drawing.PokeSprite).
    /// </summary>
    public static string PkhexName(int species, int form, bool female, int formArgument, bool cosplay, bool shiny, bool foldDefaultForm = true)
    {
        if (foldDefaultForm && DefaultFormSprite.Contains(species))
            form = 0;
        var sb = new StringBuilder(16).Append('_').Append(species);
        if (form != 0)
        {
            sb.Append('_').Append(form);
            if (species == Pikachu)
            {
                if (cosplay) sb.Append('c');
                else if (form == 8) sb.Append('p');
            }
            else if (species == Eevee && form == 1)
            {
                sb.Append('p');
            }
        }
        if (female && GenderedSprite.Contains(species))
            sb.Append('f');
        if (species == Alcremie)
        {
            if (form == 0) sb.Append('_').Append(form);
            sb.Append('_').Append(formArgument);
        }
        if (shiny) sb.Append('s');
        return sb.ToString();
    }

    /// <summary>PKHeX resource name → the asset file name ("_6_2s" → "6-2s").</summary>
    private static string FileStem(string resource) => resource[1..].Replace('_', '-');

    /// <summary>
    /// Every bundled asset to try for a look, best first. Paths are the app's logical asset
    /// names: "sprites/b_*.png" (pixel, normal + shiny) and "artwork/a_*.png" (PKHeX artwork,
    /// no shiny variants). The first one that exists wins.
    /// </summary>
    public static IReadOnlyList<SpriteCandidate> BundledCandidates(SpriteLook look)
    {
        var (species, form, shiny, t) = (look.Species, look.Form, look.Shiny, look.Traits);
        form = TotemBaseForm(species, form) ?? form;
        var list = new List<SpriteCandidate>(16);
        void Add(string path, SpriteFidelity fidelity)
        {
            if (!list.Exists(c => c.Path == path)) list.Add(new SpriteCandidate(path, fidelity));
        }
        string B(bool female, bool s, bool fold = true) => $"sprites/b_{FileStem(PkhexName(species, form, female, t.FormArgument, t.Cosplay, s, fold))}.png";
        string A(bool female, bool fold = true) => $"artwork/a_{FileStem(PkhexName(species, form, female, t.FormArgument, t.Cosplay, false, fold))}.png";

        if (t.Gigantamax)
        {
            // PKHeX names G-Max art "<species>[-form]-gmax[s]" (Urshifu keeps its style).
            var stem = species is 892 && form != 0 ? $"{species}-{form}-gmax" : $"{species}-gmax";
            if (shiny) Add($"sprites/b_{stem}s.png", SpriteFidelity.Exact);
            Add($"sprites/b_{stem}.png", shiny ? SpriteFidelity.ShinyMissing : SpriteFidelity.Exact);
        }

        var gendered = t.Female && GenderedSprite.Contains(species);
        // Exact form: pixel (shiny, then plain), then PKHeX artwork. The unfolded name comes
        // first so a real per-form asset (Urshifu Rapid Strike artwork) beats PKHeX's fold.
        foreach (var fold in form != 0 && DefaultFormSprite.Contains(species) ? new[] { false, true } : [true])
        {
            // A fold of a visibly different form is a base-form stand-in, whatever PKHeX does.
            var folded = fold && form != 0 && DefaultFormSprite.Contains(species) && !IdenticalForms.Contains(species);
            SpriteFidelity F(SpriteFidelity f) => folded ? SpriteFidelity.BaseForm : f;
            if (shiny) Add(B(t.Female, true, fold), F(SpriteFidelity.Exact));
            Add(B(t.Female, false, fold), F(shiny ? SpriteFidelity.ShinyMissing : SpriteFidelity.Exact));
            if (gendered)
            {
                if (shiny) Add(B(false, true, fold), F(SpriteFidelity.GenderMissing));
                Add(B(false, false, fold), F(shiny ? SpriteFidelity.ShinyMissing : SpriteFidelity.GenderMissing));
            }
            Add(A(t.Female, fold), F(shiny ? SpriteFidelity.ShinyMissing : SpriteFidelity.Exact));
            if (gendered) Add(A(false, fold), F(shiny ? SpriteFidelity.ShinyMissing : SpriteFidelity.GenderMissing));
        }

        // The form has no art anywhere: base form, then the placeholder.
        if (form != 0 || t.Cosplay || species == Alcremie)
        {
            var baseName = species == Alcremie ? $"{species}-0-0" : $"{species}";
            if (shiny) Add($"sprites/b_{baseName}s.png", SpriteFidelity.BaseForm);
            Add($"sprites/b_{baseName}.png", SpriteFidelity.BaseForm);
            Add($"artwork/a_{baseName}.png", SpriteFidelity.BaseForm);
        }
        Add("sprites/b_0.png", SpriteFidelity.Unknown);
        return list;
    }

    // ───────────────────────── PokeAPI HOME / Showdown ─────────────────────────

    [Flags]
    public enum Variants
    {
        None = 0,
        Normal = 1,
        Shiny = 2,
        Female = 4,
        FemaleShiny = 8,
    }

    /// <summary>One generated row: the PokeAPI file stem and which variants exist ("-" stem = none).</summary>
    public sealed record RemoteEntry(string? HomeStem, Variants Home, string? ShowdownStem, Variants Showdown);

    /// <summary>A remote file for a look, relative to PokeAPI/sprites "sprites/pokemon/other/&lt;kind&gt;/".</summary>
    /// <param name="Path">e.g. "shiny/female/10035.png".</param>
    /// <param name="CacheName">The on-device cache file name, e.g. "10035-f-s.png" (base forms keep the old "6-s.png").</param>
    public sealed record RemoteSprite(string Path, string CacheName, SpriteFidelity Fidelity);

    /// <summary>Table key of a look (see tools/SpriteForms/build.py).</summary>
    public static string TableKey(SpriteLook look)
    {
        var (species, form, t) = (look.Species, look.Form, look.Traits);
        if (t.Gigantamax && Table.Value.ContainsKey($"{species}-{form}g")) return $"{species}-{form}g";
        if (species == Pikachu && t.Cosplay && form is >= 1 and <= 6) return $"{species}-{form}c";
        if (species == Alcremie) return $"{species}-{form}-{Math.Clamp(t.FormArgument, 0, 6)}";
        return $"{species}-{form}";
    }

    /// <summary>HOME render for the exact look, or null when HOME has no art for this form.</summary>
    public static RemoteSprite? Home(SpriteLook look) =>
        Remote(look, e => (e.HomeStem, e.Home), "png");

    /// <summary>Showdown animation for the exact look, or null when none exists for this form.</summary>
    public static RemoteSprite? Showdown(SpriteLook look) =>
        Remote(look, e => (e.ShowdownStem, e.Showdown), "gif");

    private static RemoteSprite? Remote(SpriteLook look, Func<RemoteEntry, (string? Stem, Variants Flags)> pick, string ext)
    {
        if (!Table.Value.TryGetValue(TableKey(look), out var entry)) return null;
        var (stem, flags) = pick(entry);
        if (stem is null || !flags.HasFlag(Variants.Normal)) return null;

        // Shiny outranks gender: a shiny is the more visible trait. Missing variants degrade
        // to the exact form without them - never to another form.
        var female = look.Traits.Female;
        var (s, f, fidelity) = (look.Shiny, female) switch
        {
            (true, true) when flags.HasFlag(Variants.FemaleShiny) => (true, true, SpriteFidelity.Exact),
            (true, _) when flags.HasFlag(Variants.Shiny) => (true, false, female && flags.HasFlag(Variants.Female) ? SpriteFidelity.GenderMissing : SpriteFidelity.Exact),
            (true, true) when flags.HasFlag(Variants.Female) => (false, true, SpriteFidelity.ShinyMissing),
            (true, _) => (false, false, SpriteFidelity.ShinyMissing),
            (false, true) when flags.HasFlag(Variants.Female) => (false, true, SpriteFidelity.Exact),
            _ => (false, false, SpriteFidelity.Exact),
        };
        var path = $"{(s ? "shiny/" : "")}{(f ? "female/" : "")}{stem}.{ext}";
        var cache = $"{stem}{(f ? "-f" : "")}{(s ? "-s" : "")}.{ext}";
        return new RemoteSprite(path, cache, fidelity);
    }

    /// <summary>
    /// Every look the remote table knows, each variant (shiny, female) that exists at least
    /// once - the full offline pack. Different looks may share a file; dedupe by cache name.
    /// </summary>
    public static IEnumerable<SpriteLook> AllRemoteLooks()
    {
        foreach (var (key, entry) in Table.Value)
        {
            if (ParseKey(key) is not { } look) continue;
            var female = (entry.Home | entry.Showdown).HasFlag(Variants.Female);
            foreach (var shiny in new[] { false, true })
            {
                yield return look with { Shiny = shiny };
                if (female) yield return look with { Shiny = shiny, Traits = look.Traits with { Female = true } };
            }
        }
    }

    /// <summary>Inverse of <see cref="TableKey"/>.</summary>
    public static SpriteLook? ParseKey(string key)
    {
        var parts = key.Split('-');
        if (parts.Length is < 2 or > 3 || !int.TryParse(parts[0], out var species)) return null;
        var formText = parts[1];
        var traits = new SpriteTraits();
        if (formText.EndsWith('c')) { traits = traits with { Cosplay = true }; formText = formText[..^1]; }
        else if (formText.EndsWith('g')) { traits = traits with { Gigantamax = true }; formText = formText[..^1]; }
        if (!int.TryParse(formText, out var form)) return null;
        if (parts.Length == 3)
        {
            if (!int.TryParse(parts[2], out var arg)) return null;
            traits = traits with { FormArgument = arg };
        }
        return new SpriteLook(species, form, false, traits);
    }

    private static IReadOnlyDictionary<string, RemoteEntry> Load()
    {
        using var stream = typeof(SpriteCatalog).Assembly.GetManifestResourceStream("PKForge.Domain.spriteforms.tsv")
            ?? throw new InvalidOperationException("spriteforms.tsv is not embedded");
        return Parse(new StreamReader(stream, Encoding.UTF8));
    }

    internal static Dictionary<string, RemoteEntry> Parse(TextReader reader)
    {
        var map = new Dictionary<string, RemoteEntry>(StringComparer.Ordinal);
        while (reader.ReadLine() is { } line)
        {
            if (line.Length == 0 || line[0] == '#') continue;
            var p = line.Split('\t');
            if (p.Length < 5) continue;
            map[p[0]] = new RemoteEntry(
                p[1] == "-" ? null : p[1], (Variants)int.Parse(p[2]),
                p[3] == "-" ? null : p[3], (Variants)int.Parse(p[4]));
        }
        return map;
    }
}
