#!/usr/bin/env python3
"""Builds PKForge's offline dex facts: move power/accuracy/category/type + short effect,
ability short effects and item short effects, English only.

Source: PokeAPI's CSV data (https://github.com/PokeAPI/pokeapi, data/v2/csv), BSD-3-Clause,
Copyright (c) 2014 Paul Hallett and PokeAPI contributors. The notice travels inside the
generated file's header line so the shipped asset carries its own attribution. Rows the
curated prose lacks (newest moves/abilities/items) fall back to PokeAPI's English in-game
flavour text of the newest version group.

Usage:
    python3 tools/DexFacts/build.py [csv-dir] [output]
        csv-dir  a directory holding the FILES below (downloaded from PokeAPI master when omitted)
        output   defaults to src/PKForge.Domain/Resources/dexfacts.tsv.gz

The output is deterministic: rows are sorted, text is normalised, and the gzip header
carries no timestamp or file name, so an unchanged source regenerates byte-identical.

Format (UTF-8 TSV, one record per line; see PKForge.Domain.DexFacts):
    #  header / attribution
    M  id  type(0-17)  category(0 status,1 physical,2 special)  power(0 = none)  accuracy(0 = never misses)  effect
    A  id  effect
    I  normalised-english-name  effect       (items are keyed by name: item ids differ per generation)
"""
import csv
import gzip
import io
import os
import re
import sys
import unicodedata
import urllib.request

BASE = "https://raw.githubusercontent.com/PokeAPI/pokeapi/master/data/v2/csv/"
FILES = ["moves.csv", "move_effect_prose.csv", "ability_prose.csv", "item_prose.csv", "item_names.csv",
         "move_flavor_text.csv", "ability_flavor_text.csv", "item_flavor_text.csv"]
ENGLISH = "9"
ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
DEFAULT_OUT = os.path.join(ROOT, "src", "PKForge.Domain", "Resources", "dexfacts.tsv.gz")


def load(csv_dir, name):
    if csv_dir:
        with open(os.path.join(csv_dir, name), encoding="utf-8", newline="") as f:
            return list(csv.DictReader(f))
    with urllib.request.urlopen(BASE + name) as r:
        return list(csv.DictReader(io.StringIO(r.read().decode("utf-8"))))


def normalise_name(name):
    """Mirrors DexFacts.NormalizeName in C#: lower-case ASCII letters and digits only."""
    folded = unicodedata.normalize("NFKD", name)
    return "".join(ch for ch in folded.lower() if ch.isascii() and ch.isalnum())


MARKUP = re.compile(r"\[([^\]]*)\]\{[a-z-]+:([a-z0-9-]+)\}")


def clean(text, effect_chance=""):
    """PokeAPI prose markup: "[label]{kind:slug}" keeps the label (or the prettified slug);
    the move's effect chance fills "$effect_chance" or the bare "Has a chance" phrasing."""
    def repl(m):
        label, slug = m.group(1), m.group(2)
        return label if label else slug.replace("-", " ")
    text = MARKUP.sub(repl, text)
    text = text.replace("\u00ad\n", "").replace("\u00ad", "")
    if effect_chance:
        text = text.replace("$effect_chance", effect_chance)
        text = re.sub(r"\b([Hh]as) a chance\b", lambda m: "%s a %s%% chance" % (m.group(1), effect_chance), text, count=1)
    text = text.replace("$effect_chance% ", "").replace("$effect_chance", "some")
    text = re.sub(r"\s+", " ", text).strip()
    return text.replace("\t", " ")


def latest_flavor(rows, key):
    """English in-game text of the newest version group, the fallback for rows the prose lacks."""
    best = {}
    for r in rows:
        if r["language_id"] != ENGLISH or not r["flavor_text"].strip():
            continue
        group = int(r["version_group_id"])
        if r[key] not in best or group > best[r[key]][0]:
            best[r[key]] = (group, clean(r["flavor_text"]))
    return {k: v[1] for k, v in best.items()}


def main():
    csv_dir = sys.argv[1] if len(sys.argv) > 1 and sys.argv[1] != "-" else None
    out = sys.argv[2] if len(sys.argv) > 2 else DEFAULT_OUT
    data = {name: load(csv_dir, name) for name in FILES}

    effects = {r["move_effect_id"]: r["short_effect"] for r in data["move_effect_prose.csv"]
               if r["local_language_id"] == ENGLISH}
    lines = ["#\tPKForge dex facts v1 - generated by tools/DexFacts/build.py from PokeAPI data "
             "(github.com/PokeAPI/pokeapi, BSD-3-Clause, (c) 2014 Paul Hallett and PokeAPI contributors)"]

    move_flavor = latest_flavor(data["move_flavor_text.csv"], "move_id")
    ability_flavor = latest_flavor(data["ability_flavor_text.csv"], "ability_id")
    item_flavor = latest_flavor(data["item_flavor_text.csv"], "item_id")

    moves = []
    for r in data["moves.csv"]:
        move_id = int(r["id"])
        if move_id >= 10000:  # Shadow moves and other non-game rows
            continue
        category = {"1": 0, "2": 1, "3": 2}.get(r["damage_class_id"], 0)
        effect = clean(effects.get(r["effect_id"], ""), r["effect_chance"]) or move_flavor.get(r["id"], "")
        moves.append((move_id, int(r["type_id"]) - 1, category, int(r["power"] or 0), int(r["accuracy"] or 0), effect))
    for m in sorted(moves):
        lines.append("M\t%d\t%d\t%d\t%d\t%d\t%s" % m)

    ability_text = {r["ability_id"]: clean(r["short_effect"]) for r in data["ability_prose.csv"]
                    if r["local_language_id"] == ENGLISH and r["short_effect"].strip()}
    for ability_id, text in ability_flavor.items():
        ability_text.setdefault(ability_id, text)
    abilities = sorted((int(k), v) for k, v in ability_text.items() if int(k) < 10000 and v)
    for ability_id, effect in abilities:
        lines.append("A\t%d\t%s" % (ability_id, effect))

    names = {r["item_id"]: r["name"] for r in data["item_names.csv"] if r["local_language_id"] == ENGLISH}
    items = {}
    item_text = {r["item_id"]: clean(r["short_effect"]) for r in data["item_prose.csv"]
                 if r["local_language_id"] == ENGLISH and r["short_effect"].strip()}
    for item_id, text in item_flavor.items():
        item_text.setdefault(item_id, text)
    # Same-named rows (regional variants) keep the lowest id's text: stable across runs.
    for item_id in sorted(item_text, key=int):
        if item_id in names and item_text[item_id]:
            items.setdefault(normalise_name(names[item_id]), item_text[item_id])
    for key in sorted(items):
        lines.append("I\t%s\t%s" % (key, items[key]))

    payload = ("\n".join(lines) + "\n").encode("utf-8")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "wb") as raw:
        with gzip.GzipFile(filename="", mode="wb", fileobj=raw, compresslevel=9, mtime=0) as gz:
            gz.write(payload)
    print("moves %d, abilities %d, items %d -> %s (%d bytes)" % (len(moves), len(abilities), len(items), out, os.path.getsize(out)))


if __name__ == "__main__":
    main()
