using System.Reflection;
using PKForge.Engine.RadicalRed;
using PKForge.Engine.Unbound;
using PKHeX.Core;

namespace PKForge.Engine.GsChronicles;

/// <summary>
/// Pokémon GS Chronicles' tables, generated by tools/GscTables/generate.py from the
/// game's own engine source (github.com/G0LD/GS-Chronicles-Engine @7517ab2): species,
/// national dex numbers, moves, move PP, abilities and items, each keyed by the id the
/// save stores. Every id crosses into PKHeX's national space here:
/// <list type="bullet">
/// <item>species through species_national.txt, pokedex.h's NATIONAL_DEX_ numbering,
/// which is what the save's dex bitmaps index (the real save's only dex bit is 481,
/// its party Mesprit, stored as species 534). It is the modern national number
/// through 905; GSC gives 906-910 to Annihilape..Clodsire, which bridge by name;</item>
/// <item>moves, items and abilities by normalized name against PKHeX's lists. An item
/// id that items.h names twice ("Rocky Helmet / Choice Specs") has no single name and
/// deliberately stays unbridged rather than guessing.</item>
/// </list>
/// Base stats, types, gender, abilities and growth come from the national tables
/// (<see cref="CfruNationalTraits"/>); GSC originals with no national number
/// (Shadow Warrior) fall back to neutral values.
/// </summary>
internal sealed class GsChroniclesData : ICfruGameData
{
    public static readonly GsChroniclesData Instance = new();

    private readonly Lazy<Tables> _tables = new(Load, LazyThreadSafetyMode.ExecutionAndPublication);

    private GsChroniclesData() { }

    private Tables T => _tables.Value;

    /// <summary>GSC's pokedex.h follows the national order through Enamorus.</summary>
    private const int RetailDexLimit = 905;

    private sealed record Tables(
        Dictionary<int, string> Species,
        Dictionary<int, int> NationalBySpecies,
        Dictionary<int, int> SpeciesByNational,
        Dictionary<int, int> DexByNational,
        Dictionary<int, string> Moves,
        Dictionary<int, int> MovePp,
        Dictionary<int, string> Items,
        Dictionary<int, string> Abilities,
        CfruIdBridge MoveBridge,
        CfruIdBridge ItemBridge,
        CfruIdBridge AbilityBridge,
        GameStrings Strings,
        int MaxSpecies,
        int MaxItem);

    private static Tables Load()
    {
        var strings = GameInfo.GetStrings("en");
        var species = LoadTable("gschronicles.species.txt");
        var dexBySpecies = LoadTable("gschronicles.species_national.txt")
            .ToDictionary(pair => pair.Key, pair => int.Parse(pair.Value, System.Globalization.CultureInfo.InvariantCulture));
        var speciesByDex = new Dictionary<int, int>();
        foreach (var (id, dex) in dexBySpecies.OrderBy(pair => pair.Key))
            speciesByDex.TryAdd(dex, id); // the base form is the lowest id

        // Dex numbers past the retail-aligned zone name their species through the base
        // form's name ("Annihilape" is GSC dex 906, national 979).
        var nationalByName = new Dictionary<string, int>();
        for (var id = 1; id < strings.specieslist.Length; id++)
            nationalByName.TryAdd(UnboundData.NormalizeName(strings.specieslist[id]), id);
        var nationalByDex = new Dictionary<int, int>();
        foreach (var (dex, baseSpecies) in speciesByDex)
        {
            if (dex <= RetailDexLimit)
                nationalByDex[dex] = dex;
            else if (nationalByName.TryGetValue(UnboundData.NormalizeName(species[baseSpecies]), out var national))
                nationalByDex[dex] = national;
        }
        var nationalBySpecies = dexBySpecies
            .Where(pair => nationalByDex.ContainsKey(pair.Value))
            .ToDictionary(pair => pair.Key, pair => nationalByDex[pair.Value]);
        var byNational = nationalByDex.ToDictionary(pair => pair.Value, pair => speciesByDex[pair.Key]);
        var dexByNational = nationalByDex.ToDictionary(pair => pair.Value, pair => pair.Key);
        var moves = LoadTable("gschronicles.moves.txt");
        var movePp = LoadTable("gschronicles.movepp.txt")
            .ToDictionary(pair => pair.Key, pair => int.Parse(pair.Value, System.Globalization.CultureInfo.InvariantCulture));
        var items = LoadTable("gschronicles.items.txt");
        var abilities = LoadTable("gschronicles.abilities.txt");
        return new Tables(species, nationalBySpecies, byNational, dexByNational, moves, movePp, items, abilities,
            new CfruIdBridge(moves, strings.movelist, []),
            new CfruIdBridge(items, strings.itemlist, []),
            new CfruIdBridge(abilities, strings.abilitylist, []),
            strings, species.Keys.Max(), items.Keys.Max());
    }

    /// <summary>Generator tables: `id&lt;TAB&gt;value` with `#` provenance comments.</summary>
    private static Dictionary<int, string> LoadTable(string resource)
    {
        var map = new Dictionary<int, string>(2048);
        using var stream = Assembly.GetExecutingAssembly().GetManifestResourceStream(resource)
            ?? throw new InvalidOperationException($"Missing embedded resource {resource}.");
        using var reader = new StreamReader(stream);
        while (reader.ReadLine() is { } line)
        {
            if (line.Length == 0 || line[0] == '#') continue;
            var separator = line.IndexOf('\t');
            if (separator > 0 && int.TryParse(line.AsSpan(0, separator), out var id))
                map[id] = line[(separator + 1)..];
        }
        return map;
    }

    // ── Species ──

    public int MaxSpeciesId => T.MaxSpecies;
    public bool IsKnownSpecies(int species) => species > 0 && T.Species.ContainsKey(species);
    public string SpeciesName(int species) => T.Species.TryGetValue(species, out var name) ? name : $"#{species}";
    public int NationalIdOf(int species) => T.NationalBySpecies.TryGetValue(species, out var national) ? national : 0;
    public int SpeciesFromNational(int national) => T.SpeciesByNational.TryGetValue(national, out var species) ? species : 0;
    public int DexNumberOf(int national) => T.DexByNational.TryGetValue(national, out var dex) ? dex : 0;

    /// <summary>A GSC species id for a PKHeX (national) species name, or for the
    /// table's own name ("Vulpix-Alola"); 0 when neither knows it.</summary>
    public int SpeciesIdByName(string name)
    {
        if (name.Length == 0) return 0;
        var key = UnboundData.NormalizeName(name);
        var list = T.Strings.specieslist;
        for (var national = 1; national < list.Length; national++)
            if (UnboundData.NormalizeName(list[national]) == key)
                return SpeciesFromNational(national);
        foreach (var (id, own) in T.Species.OrderBy(pair => pair.Key))
            if (UnboundData.NormalizeName(own) == key)
                return id;
        return 0;
    }

    // ── Moves ──

    public string MoveName(int move) => T.Moves.TryGetValue(move, out var name) ? name : $"#{move}";
    public int MoveToNational(int move) => move == 0 ? 0 : T.MoveBridge.ToNational(move);
    public int MoveFromNational(int national) => national == 0 ? 0 : T.MoveBridge.FromNational(national);
    public int MoveBasePp(int move) => T.MovePp.TryGetValue(move, out var pp) ? pp : 0;

    public int MoveIdByName(string name)
    {
        if (name.Length == 0) return 0;
        var list = T.Strings.movelist;
        for (var id = 1; id < list.Length; id++)
            if (list[id].Equals(name, StringComparison.OrdinalIgnoreCase))
                return MoveFromNational(id);
        return 0;
    }

    // ── Items and bag pockets ──
    // The ROM's item table (with each item's pocket) is not part of the engine source,
    // so pocket families follow the names: balls end in " Ball" (bar the held Smoke /
    // Light / Iron Ball), berries in " Berry", machines are TMxx/HMxx, and key items are
    // FireRed's key-item id zones 259-288 and 347-374, which items.h keeps in place.
    // They only steer the add-item pickers: the bag itself is read by pocket position.

    public int MaxItemId => T.MaxItem;
    public string ItemName(int item) => T.Items.TryGetValue(item, out var name) ? name : $"#{item}";
    public int ItemToNational(int item) => item == 0 ? 0 : T.ItemBridge.ToNational(item);
    public int ItemFromNational(int national) => national == 0 ? 0 : T.ItemBridge.FromNational(national);
    public bool IsFillerItem(int item) => !T.Items.ContainsKey(item);

    private readonly Lazy<Dictionary<string, HashSet<int>>> _pockets = new(() => BuildPockets(Instance.T.Items));

    public IReadOnlyCollection<int> PocketIds(string family) =>
        _pockets.Value.TryGetValue(family, out var ids) ? ids : [];

    public bool IsSpecialPocketItem(int item) => _pockets.Value.Values.Any(ids => ids.Contains(item));

    private static Dictionary<string, HashSet<int>> BuildPockets(Dictionary<int, string> items)
    {
        HashSet<int> ball = [], berry = [], machine = [], key = [];
        foreach (var (id, name) in items)
        {
            if (name.EndsWith(" Ball", StringComparison.Ordinal) && name is not ("Smoke Ball" or "Light Ball" or "Iron Ball"))
                ball.Add(id);
            else if (name.EndsWith(" Berry", StringComparison.Ordinal))
                berry.Add(id);
            else if (name.Split(" / ").All(IsMachineName))
                machine.Add(id);
            else if (id is >= 259 and <= 288 or >= 347 and <= 374)
                key.Add(id);
        }
        return new Dictionary<string, HashSet<int>> { ["ball"] = ball, ["berry"] = berry, ["tm"] = machine, ["key"] = key };
    }

    private static bool IsMachineName(string name) =>
        name.Length > 2 && name[1] == 'M' && name[0] is 'T' or 'H' && name[2..].All(char.IsAsciiDigit);

    // ── Abilities ──
    // The save stores no ability id (the PID's low bit plus the hidden flag select one
    // of the species' slots), so abilities resolve through the national tables and
    // display with PKHeX's names; the ROM table only names what PKHeX lacks.

    public string AbilityName(int ability)
    {
        var list = T.Strings.abilitylist;
        if (ability > 0 && ability < list.Length && list[ability].Length > 0) return list[ability];
        var own = T.AbilityBridge.FromNational(ability);
        return own > 0 && T.Abilities.TryGetValue(own, out var name) ? name : $"#{ability}";
    }

    public (int A1, int A2, int Hidden) AbilityIds(int species) => CfruNationalTraits.AbilityIds(NationalIdOf(species));
    public int ActiveAbility(RadicalRedMon mon) => CfruNationalTraits.ActiveAbility(mon, NationalIdOf(mon.Species));

    // ── National-derived traits ──

    public int[] BaseStats(int species) => CfruNationalTraits.BaseStats(NationalIdOf(species));
    public int[] TypesOf(int species) => CfruNationalTraits.TypesOf(NationalIdOf(species));
    public int GenderOf(uint pid, int species) => CfruNationalTraits.GenderOf(pid, NationalIdOf(species));
    public int GenderThreshold(int species) => CfruNationalTraits.GenderThreshold(NationalIdOf(species));
    public uint ExperienceAtLevel(int species, int level) => CfruNationalTraits.ExperienceAtLevel(NationalIdOf(species), level);
    public int LevelForExperience(int species, uint experience) =>
        CfruNationalTraits.LevelForExperience(NationalIdOf(species), experience);
    public int[] ComputeStats(RadicalRedMon mon) => CfruNationalTraits.ComputeStats(mon, NationalIdOf(mon.Species));
}
