#!/usr/bin/env python3
"""Generates PKForge's Pokémon GS Chronicles data tables from the game's engine source.

Usage: python3 generate.py <GS-Chronicles-Engine checkout> <output directory>

Source: github.com/G0LD/GS-Chronicles-Engine (Ruki Studios' CFRU fork), pinned at
PINNED_COMMIT below; the script refuses any other checkout so a table can never
silently drift from the commit its header cites. Output is deterministic (sorted,
no timestamps), so re-running it on the pinned commit is a no-op diff.

Inputs, all read-only:
  include/constants/species.h   species ids (SPECIES_*)
  include/constants/pokedex.h   national dex numbers (NATIONAL_DEX_*), the same
                                numbering the save's dex bitmaps use
  include/constants/moves.h     move ids (MOVE_*)
  strings/attack_name_table_long.string  gLongMoveNames, the ROM's full move names by id
  include/constants/abilities.h ability ids (ABILITY_*)
  strings/ability_name_table.string  the ROM's ability names, in id order
  src/Tables/battle_moves.c     gBattleMoves, for each move's base PP
  include/constants/items.h     item ids (ITEM_*), UNBOUND left undefined (GSC's
                                src/config.h never defines it)

Outputs (`id<TAB>value`, `#` provenance comments; the format of the Radical Red tables):
  species.txt           species id -> display name
  species_national.txt  species id -> GSC Pokédex number (forms map to their base). This is
                        the number the save's dex bitmaps index; it equals the modern national
                        number through 905 (Enamorus), while 906-910 are GSC's own slots for
                        Annihilape..Clodsire (national 979, 981, 982, 983 and 980), which the
                        app bridges by name.
  moves.txt             move id -> name
  movepp.txt            move id -> base PP (src/Tables/battle_moves.c)
  abilities.txt         ability id -> name
  items.txt             item id -> display name
"""
import os
import re
import subprocess
import sys

PINNED_COMMIT = "7517ab241b5f05145b1373494a9df407a324dd42"
REPO = "github.com/G0LD/GS-Chronicles-Engine"

NUMBER = r"(0x[0-9A-Fa-f]+|\d+)"

# Size constants that share a header with the ids (moves.h: MOVE_NAME_LENGTH 12 = Guillotine).
NON_ID_CONSTANTS = {"NAME_LENGTH"}

# ── Species ──

# National names whose punctuation the C identifier cannot carry.
SPECIES_NAME_FIXUPS = {
    "NIDORAN_F": "Nidoran♀", "NIDORAN_M": "Nidoran♂", "FARFETCHD": "Farfetch'd",
    "MR_MIME": "Mr. Mime", "HO_OH": "Ho-Oh", "MIME_JR": "Mime Jr.", "PORYGON_Z": "Porygon-Z",
    "FLABEBE": "Flabébé", "TYPE_NULL": "Type: Null", "JANGMO_O": "Jangmo-o",
    "HAKAMO_O": "Hakamo-o", "KOMMO_O": "Kommo-o", "SIRFETCHD": "Sirfetch'd", "MR_RIME": "Mr. Rime",
}

# Species constants whose base is not a NATIONAL_DEX_ prefix (glued or aliased names).
SPECIES_BASE_OVERRIDES = {"FARFETCHED": ("FARFETCHD", ""), "DARMANITANZEN": ("DARMANITAN", "ZEN"),
                          "ASHGRENINJA": ("GRENINJA", "ASH")}

# Engine placeholders with no national counterpart; SHADOW_WARRIOR is a GSC original.
SPECIES_WITHOUT_NATIONAL = {"MISSINGNO", "EGG", "SHADOW_WARRIOR", "GMAX_DUMMY"}

# Regional-form letters (CFRU's _A/_G/_H/_P); every other form token is title-cased.
FORM_TOKENS = {"A": "Alola", "G": "Galar", "H": "Hisui", "P": "Paldea"}
LETTER_FORM_BASES = {"UNOWN"}  # Unown's single letters are its forms, not regions

# ── Items ──

ITEM_WORD_FIXUPS = {"Poke": "Poké", "Pokedex": "Pokédex", "Pokeblock": "Pokéblock", "Pokeflute": "Poké Flute"}
# Whole-name punctuation the C identifier cannot carry (retail spellings).
ITEM_NAME_FIXUPS = {
    "KINGS_ROCK": "King's Rock", "EXP_SHARE": "Exp. Share", "SS_TICKET": "S.S. Ticket",
    "NEVER_MELT_ICE": "Never-Melt Ice", "UP_GRADE": "Up-Grade", "X_ATTACK": "X Attack",
    "OAKS_PARCEL": "Oak's Parcel", "TM_CASE": "TM Case", "VS_SEEKER": "VS Seeker", "TEACHY_TV": "Teachy TV",
}


def die(message):
    sys.exit(f"generate.py: {message}")


def read(root, relative):
    with open(os.path.join(root, relative), encoding="utf-8") as handle:
        return handle.read()


def check_commit(root):
    try:
        head = subprocess.check_output(["git", "-C", root, "rev-parse", "HEAD"], text=True).strip()
    except (OSError, subprocess.CalledProcessError) as error:
        die(f"cannot read the checkout's commit: {error}")
    if head != PINNED_COMMIT:
        die(f"checkout is at {head}, expected the pinned {PINNED_COMMIT}")


def title(identifier):
    return " ".join(part.capitalize() for part in identifier.split("_") if part)


def header(source, note):
    lines = [
        f"# Pokémon GS Chronicles (Ruki Studios, CFRU FireRed hack): {note}",
        f"# Generated by tools/GscTables/generate.py from {REPO} @{PINNED_COMMIT}",
        f"# Source: {source}. Do not edit by hand; re-run the generator instead.",
    ]
    return "\n".join(lines) + "\n"


def write(out_dir, name, head, rows):
    with open(os.path.join(out_dir, name), "w", encoding="utf-8", newline="\n") as handle:
        handle.write(head)
        for key, value in sorted(rows.items()):
            handle.write(f"{key}\t{value}\n")


def numeric_defines(text, prefix):
    """`#define PREFIX_NAME <number>` in file order; aliases and expressions are skipped."""
    pattern = re.compile(rf"^#define {prefix}_(\w+)\s+{NUMBER}\b", re.MULTILINE)
    return [(match.group(1), int(match.group(2), 0)) for match in pattern.finditer(text)]


def string_table(text):
    """A .string table's entries in order: (label, text) after the table label."""
    entries = []
    for block in re.split(r"^#org @", text, flags=re.MULTILINE)[1:]:
        label, _, body = block.partition("\n")
        entries.append((label.strip(), body.strip()))
    return entries


def name_key(identifier):
    return re.sub(r"[^A-Z0-9]", "", identifier.upper())


def generate_species(root):
    species = {}
    for name, value in numeric_defines(read(root, "include/constants/species.h"), "SPECIES"):
        if name == "NONE":
            continue
        species.setdefault(value, []).append(name)
    dex = dict(numeric_defines(read(root, "include/constants/pokedex.h"), "NATIONAL_DEX"))
    dex.pop("NONE", None)

    names, national = {}, {}
    for species_id, constants in species.items():
        # Aliased ids (FARFETCHED/FARFETCHD) keep the spelling the dex table uses.
        constant = next((c for c in constants if c in dex), constants[0])
        if constant in SPECIES_WITHOUT_NATIONAL:
            names[species_id] = title(constant)
            continue
        if constant in SPECIES_BASE_OVERRIDES:
            base, suffix = SPECIES_BASE_OVERRIDES[constant]
        else:
            candidates = [b for b in dex if constant == b or constant.startswith(b + "_")]
            if not candidates:
                die(f"SPECIES_{constant} ({species_id}) has no national base; extend the override tables")
            base = max(candidates, key=len)
            suffix = constant[len(base) + 1:]
        display = SPECIES_NAME_FIXUPS.get(base, title(base))
        if suffix:
            tokens = suffix.split("_")
            if base not in LETTER_FORM_BASES:
                tokens = [FORM_TOKENS.get(token, token) for token in tokens]
            display += "-" + "-".join(token if token in FORM_TOKENS.values() else token.capitalize()
                                      for token in tokens)
        names[species_id] = display
        national[species_id] = dex[base]
    return names, national


def generate_indexed(root, header_path, prefix, table_path, table_limit=None):
    """Ids from a constants header, names from the ROM's fixed-width string table,
    which the engine indexes by id (gLongMoveNames[move], gAbilityNames[ability]).
    Ids at or past table_limit are not in the table (the Z-moves live in their own
    gZMoveNames and the long move table skips them), so they are title-cased from
    their constant instead. Alignment is proven, not assumed: a label that names
    the NEIGHBOURING id's constant means the table shifted, which aborts; a label
    that merely spells the same move differently (VICEGRIP vs NAME_LONG_VISE_GRIP)
    is reported as a rename."""
    ids = {}
    for name, value in numeric_defines(read(root, header_path), prefix):
        if name not in NON_ID_CONSTANTS:
            ids.setdefault(value, name)
    entries = string_table(read(root, table_path))[1:]  # drop the table's own label
    limit = table_limit if table_limit is not None else len(entries)
    names, renames = {}, []
    for index in sorted(ids):
        if index == 0:
            continue
        if index >= limit or index >= len(entries):
            names[index] = title(ids[index])
            continue
        label, text = entries[index]
        label_key = name_key(re.sub(r"^(NAME_(LONG_)?|gText_AbilityName_)", "", label))
        if label_key != name_key(ids[index]):
            neighbours = {name_key(ids.get(index - 1, "")), name_key(ids.get(index + 1, ""))}
            if label_key in neighbours:
                die(f"{table_path} is shifted at {index}: label {label} names a neighbouring id")
            renames.append((index, ids[index], label))
        names[index] = text
    return names, ids, renames


def generate_items(root):
    """items.h is a small C program: #ifdef UNBOUND blocks (never taken for GSC),
    plain numeric defines, and enums that count up from their last explicit value."""
    lines = read(root, "include/constants/items.h").splitlines()
    skipping = []  # stack of booleans: True while inside a branch that is not compiled
    defined = {}
    order = []
    in_enum = False
    next_value = 0
    for raw in lines:
        line = raw.split("//", 1)[0].strip()
        if not line:
            continue
        if line.startswith("#ifdef ") or line.startswith("#ifndef "):
            taken = (line.split()[1] == "UNBOUND") == line.startswith("#ifndef ")
            if line.split()[1] != "UNBOUND":
                die(f"unexpected conditional: {raw}")
            skipping.append(not taken)
            continue
        if line.startswith("#else"):
            skipping[-1] = not skipping[-1]
            continue
        if line.startswith("#endif"):
            skipping.pop()
            continue
        if any(skipping):
            continue
        if line.startswith("#undef "):
            defined.pop(line.split()[1], None)
            continue
        if line == "enum":
            in_enum, next_value = True, 0
            continue
        if in_enum:
            if line.startswith("{"):
                continue
            if line.startswith("}"):
                in_enum = False
                continue
            for member in filter(None, (part.strip() for part in line.split(","))):
                name, _, value = (part.strip() for part in member.partition("="))
                if value:
                    next_value = resolve(value, defined)
                if name.startswith("ITEM_"):
                    defined[name] = next_value
                    order.append(name)
                next_value += 1
            continue
        match = re.match(r"#define (ITEM_\w+)\s+(.+)$", line)
        if match:
            value = resolve(match.group(2).strip(), defined, strict=False)
            if value is not None:
                defined[match.group(1)] = value
                order.append(match.group(1))
    # Several constants can land on one id. items.h first reserves placeholder
    # slots (ITEM_0E2 ...) that later lines redefine, which is harmless: the
    # placeholders are dropped. But it ALSO gives real, differently named items
    # the same id (ITEM_ROCKY_HELMET and ITEM_CHOICE_SPECS are both 0xE2, and the
    # engine code references both), and the header alone cannot say which name the
    # ROM's item table carries. Those ids are named "A / B" in file order instead
    # of guessing; the name bridge then leaves them unmapped rather than wrong.
    by_id = {}
    for name in order:
        value = defined.get(name)
        if value is None or value <= 0 or name in {"ITEM_LAST_INDEX", "ITEMS_COUNT"}:
            continue
        if re.fullmatch(r"ITEM_[0-9A-F]{3}", name) or name == "ITEM_N_A":
            continue  # unnamed placeholder slots
        names = by_id.setdefault(value, [])
        if name not in names:
            names.append(name)
    items, collisions = {}, []
    for value, names in by_id.items():
        displays = list(dict.fromkeys(item_display(name[len("ITEM_"):]) for name in names))
        if len(displays) > 1:
            collisions.append((value, names))
        items[value] = " / ".join(displays)
    return items, collisions


def generate_move_pp(root, move_ids):
    """Base PP from gBattleMoves' designated initializers ([MOVE_X] = { ... .pp = N })."""
    text = read(root, "src/Tables/battle_moves.c")
    by_constant = {name: value for value, name in move_ids.items()}
    pp = {}
    for match in re.finditer(r"\[MOVE_(\w+)\]\s*=\s*\{(.*?)\n\t\}", text, re.DOTALL):
        value = by_constant.get(match.group(1))
        field = re.search(r"\.pp\s*=\s*(\d+)", match.group(2))
        if value is not None and value > 0 and field:
            pp[value] = int(field.group(1))
    return pp


def first_z_move(root):
    for name, value in numeric_defines(read(root, "include/constants/moves.h"), "MOVE"):
        if name == "BREAKNECK_BLITZ_P":
            return value
    die("MOVE_BREAKNECK_BLITZ_P not found")


def resolve(expression, defined, strict=True):
    expression = expression.strip().strip("()")
    match = re.fullmatch(NUMBER, expression)
    if match:
        return int(expression, 0)
    match = re.fullmatch(r"(ITEM_\w+)\s*([+-])\s*" + NUMBER, expression)
    if match and match.group(1) in defined:
        offset = int(match.group(3), 0)
        return defined[match.group(1)] + (offset if match.group(2) == "+" else -offset)
    if expression in defined:
        return defined[expression]
    if strict:
        die(f"cannot resolve item expression: {expression}")
    return None


def item_display(identifier):
    if identifier in ITEM_NAME_FIXUPS:
        return ITEM_NAME_FIXUPS[identifier]
    machine = re.fullmatch(r"(TM|HM)(\d+)(_\w+)?", identifier)
    if machine:
        return f"{machine.group(1)}{machine.group(2)}"
    words = [ITEM_WORD_FIXUPS.get(word, word) for word in title(identifier).split(" ")]
    return " ".join(words)


def main():
    if len(sys.argv) != 3:
        die("usage: generate.py <GS-Chronicles-Engine checkout> <output directory>")
    root, out_dir = sys.argv[1], sys.argv[2]
    check_commit(root)
    os.makedirs(out_dir, exist_ok=True)

    species, national = generate_species(root)
    write(out_dir, "species.txt",
          header("include/constants/species.h + pokedex.h",
                 "species id -> display name (national name, '-Form' for form slots)"), species)
    write(out_dir, "species_national.txt",
          header("include/constants/species.h + pokedex.h (longest NATIONAL_DEX_ prefix of each SPECIES_ constant)",
                 "species id -> GSC Pokédex number (forms map to their base species; "
                 "equal to the national number through 905, GSC's own numbering past it)"), national)

    moves, move_ids, move_mismatches = generate_indexed(
        root, "include/constants/moves.h", "MOVE", "strings/attack_name_table_long.string",
        table_limit=first_z_move(root))
    write(out_dir, "moves.txt",
          header("include/constants/moves.h + strings/attack_name_table_long.string (gLongMoveNames, id-indexed; "
                 "Z-/Max-move names from their constants)",
                 "move id -> ROM move name"), moves)

    move_pp = generate_move_pp(root, move_ids)
    write(out_dir, "movepp.txt",
          header("src/Tables/battle_moves.c (gBattleMoves[].pp)", "move id -> base PP"), move_pp)

    abilities, ability_ids, ability_mismatches = generate_indexed(
        root, "include/constants/abilities.h", "ABILITY", "strings/ability_name_table.string")
    write(out_dir, "abilities.txt",
          header("include/constants/abilities.h + strings/ability_name_table.string (id order)",
                 "ability id -> ROM ability name"), abilities)

    items, item_collisions = generate_items(root)
    write(out_dir, "items.txt",
          header("include/constants/items.h (UNBOUND undefined, as in src/config.h)",
                 "item id -> display name (from the ITEM_ constants; ids items.h defines "
                 "under two real names are listed as 'A / B')"), items)

    print(f"species {len(species)} (national {len(national)}), moves {len(moves)}/{len(move_ids)}, "
          f"move pp {len(move_pp)}, abilities {len(abilities)}/{len(ability_ids)}, items {len(items)}")
    for value, names in sorted(item_collisions):
        print(f"  item {value}: {' < '.join(names)} (ambiguous, named with every candidate)")
    for kind, renames in (("move", move_mismatches), ("ability", ability_mismatches)):
        for index, constant, label in renames:
            print(f"  {kind} {index}: constant {constant}, table label {label} (same slot, different spelling)")


if __name__ == "__main__":
    main()
